version: 0
language: en
database:
  type: sqlite
  path: plugins/Bolt/bolt.db
  hostname: ""
  database: ""
  username: ""
  password: ""
  prefix: ""
  properties: [ ]
protections:
  private: [ ]
  redstone: [ "redstone" ]
  display: [ "interact", "open" ]
  deposit: [ "interact", "open", "deposit" ]
  withdrawal: [ "interact", "open", "withdraw" ]
  public: [ "interact", "open", "deposit", "withdraw", "mount" ]
access:
  normal: [ "interact", "open", "deposit", "withdraw", "mount" ]
  admin: [ "interact", "open", "deposit", "withdraw", "mount", "edit" ]
blocks:
  chest:
    autoProtect: private
  trapped_chest:
    autoProtect: private
  furnace:
    autoProtect: private
  blast_furnace:
    autoProtect: private
  smoker:
    autoProtect: private
  dispenser:
    autoProtect: private
  dropper:
    autoProtect: private
  barrel:
    autoProtect: private
  composter:
    autoProtect: private
  lectern:
    autoProtect: private
  hopper:
    autoProtect: private
  '#shulker_boxes':
    autoProtect: private
  '#signs':
    autoProtect: false
  '#doors':
    autoProtect: false
  '#trapdoors':
    autoProtect: false
  '#fence_gates':
    autoProtect: false
  '#banners':
    autoProtect: false
entities:
  armor_stand:
    autoProtect: private
  item_frame:
    autoProtect: private
  glow_item_frame:
    autoProtect: private
  chest_boat:
    autoProtect: false
  minecart_chest:
    autoProtect: false
  minecart_furnace:
    autoProtect: false
  minecart_hopper:
    autoProtect: false
